export default {
  name: 'siteSettings', title: 'Site Settings', type: 'document',
  fieldsets: [
    { name: 'themeAudio', title: 'Theme audio', description: 'Site-wide theme tune ("Audio Log"). Click-to-play, persists across pages.', options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    { name: 'siteName', title: 'Site Name', type: 'string', initialValue: 'Labrats' },
    { name: 'tagline', title: 'Tagline', type: 'string', initialValue: 'Where Genius Meets Mischief!' },
    { name: 'siteDescription', title: 'Site Description', type: 'text', rows: 3, initialValue: 'Labrats is an animated sci-fi series following genetically enhanced lab rats fighting for freedom. Explore the book series, meet the characters, and join the rebellion.' },
    { name: 'contactEmail', title: 'Contact Email', type: 'string', initialValue: 'contact@labrats.uk' },
    { name: 'youtubeChannel', title: 'YouTube Channel URL', type: 'url' },
    { name: 'socialLinks', title: 'Social Links', type: 'array', of: [{ type: 'object', fields: [{ name: 'platform', title: 'Platform', type: 'string', options: { list: ['Instagram', 'TikTok', 'X', 'Facebook', 'YouTube', 'Threads'] } }, { name: 'url', title: 'URL', type: 'url' }] }] },
    { name: 'announcementBar', title: 'Announcement Bar', type: 'string' },
    { name: 'logo', title: 'Logo', type: 'image' },
    { name: 'footerLogo', title: 'Footer Logo', type: 'image' },
    { name: 'footerText', title: 'Footer Text', type: 'text', rows: 2, initialValue: '© The Metavision 2026. All rights reserved.' },
    { name: 'newsletterHeadline', title: 'Newsletter Headline', type: 'string', initialValue: 'Join the Rebellion' },
    { name: 'newsletterSubtext', title: 'Newsletter Subtext', type: 'string', initialValue: 'Lab dispatches, mission reports, and first access to merch drops.' },
    { name: 'heroImage', title: 'Hero Background Image', type: 'image', options: { hotspot: true }, description: 'Full-width background image for the homepage hero section' },
    { name: 'heroPortrait', title: 'Hero Portrait Image', type: 'image', options: { hotspot: true }, description: 'Character portrait overlay on the hero (optional)' },
    { name: 'bookPromoImage', title: 'Book Promo Image', type: 'image', options: { hotspot: true }, description: 'Book series promo image shown on the homepage' },
    { name: 'trailerYoutubeUrl', title: 'Trailer YouTube URL', type: 'url', description: 'YouTube URL for the homepage trailer CTA' },
    { name: 'storeOpenDate', title: 'Store Open Date', type: 'datetime', description: 'Countdown target date for the merch store launch' },
    { name: 'themeTrackTitle', title: 'Theme track title', type: 'string', fieldset: 'themeAudio', description: 'Display title for the theme tune. Surfaces in expanded-state tooltip and ARIA fallbacks.', initialValue: 'Labrats Main Theme', validation: (Rule) => Rule.max(80) },
    { name: 'themeTrackArtist', title: 'Theme track composer / artist credit', type: 'string', fieldset: 'themeAudio', description: 'Optional. Composer or artist credit. Shown in expanded-state if present.', initialValue: '[Composer credit TBC — Alan to confirm]', validation: (Rule) => Rule.max(120) },
    { name: 'themeAudioFile', title: 'Theme audio file (.mp3)', type: 'file', fieldset: 'themeAudio', description: 'Upload the .mp3 here. The original .wav stays on the local master. Sanity serves the .mp3 from its CDN — no R2 needed.', options: { accept: 'audio/mpeg,audio/mp3' } },
    { name: 'themeEnabled', title: 'Theme audio enabled', type: 'boolean', fieldset: 'themeAudio', description: 'Master kill switch. Set to false to hide the control across the entire site without a code deploy.', initialValue: true },
    { name: 'themeAutoplayPolicy', title: 'Autoplay policy', type: 'string', fieldset: 'themeAudio', description: 'Reserved for future flexibility. Currently only "click-to-play" is supported by the component.', initialValue: 'click-to-play', options: { list: [{ title: 'Click to play (default — recommended)', value: 'click-to-play' }], layout: 'radio' }, readOnly: true },
  ],
  __experimental_actions: ['update', 'publish'],
};
